version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "passive-display-renderer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bh982fcld2qm"
s3_prefix = "passive-display-renderer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
