AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Passive Display Renderer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# Globals:
#   Function:
#     Timeout: 3
#     Tracing: Active
#   Api:
#     TracingEnabled: True

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
  S3SecretsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  SnapshotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda.handler
      Runtime: nodejs16.x
      Timeout: 15
      MemorySize: 4096
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:764866452798:layer:chrome-aws-lambda:31"
      Environment:
        Variables:
          TARGET_URL: "https://google.com"
          S3_BUCKET: !Ref S3Bucket
          S3_SECRETS_BUCKET: !Ref S3SecretsBucket
          S3_SECRETS_KEY: "secrets.json"
          DISPLAY_HEIGHT: "825px"
          DISPLAY_WIDTH: "1200px"
          DAY_COUNT: 4
          TIME_ZONE: "America/New_York"
          TIME_LOCALE: "en-US"
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3Bucket

      Events:
        SnapshotEvent:
          Type: Schedule
          Properties:
            Schedule: rate(6 hours)
        # GenerateImageRequest:
        #   Type: Api
        #   Properties:
        #     Path: /generate
        #     Method: get
Outputs:
  ConsumerFunction:
    Description: SnapshotFunction function name
    Value: !Ref SnapshotFunction
# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   GenerateImageApi:
#     Description: "API Gateway endpoint URL for Prod stage for Generate Image function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   GenerateImageFunction:
#     Description: "Generate Image Lambda Function ARN"
#     Value: !GetAtt GenerateImageFunction.Arn
#   GenerateImageFunctionIamRole:
#     Description: "Implicit IAM Role created for Generate Image function"
#     Value: !GetAtt GenerateImageFunctionRole.Arn
